version: 1.0.{build}
image:
- Visual Studio 2017
- Visual Studio 2015
test: off
build:
  parallel: true
platform:
- x64
environment:
  matrix:
  - PYTHON: 36
    CPP: 14
    CONFIG: Release
  - PYTHON: 36
    CPP: latest
    CONFIG: Release
matrix:
  exclude:
    - image: Visual Studio 2015
      CPP: latest
install:
- ps: |
    if ($env:PLATFORM -eq "x64") { $env:CMAKE_ARCH = "x64" }
    if ($env:APPVEYOR_JOB_NAME -like "*Visual Studio 2017*") {
      $env:CMAKE_GENERATOR = "Visual Studio 15 2017"
    } else {
      $env:CMAKE_GENERATOR = "Visual Studio 14 2015"
    }
    if ($env:PYTHON) {
      if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64" }
      $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
      pip install --disable-pip-version-check --user --upgrade pip wheel
      pip install pytest numpy
    }
build_script:
- mkdir build
- cd build
- cmake -G "%CMAKE_GENERATOR%" -A "%CMAKE_ARCH%" ../src
- cmake --build . --config %CONFIG% --target ALL_BUILD
