env:
  global:
    - SHARED=OFF

matrix:

  notifications:
    email: false # turn off email notifications for build failure

  include:
    # Default environment of Ubuntu 14.04
    - os: linux
      dist: trusty
      sudo: true
      language: python
      python: "3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - g++-4.8
            - cmake-data # to use cmake 3.0 or more recent
            - cmake

    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: "3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - g++-4.8
            - cmake-data # to use cmake 3.0 or more recent
            - cmake
      env: SHARED=ON

    # Similar environment of Ubuntu 16.04 (gcc 5.4)
    # travis ci only supports Ubuntu 14.04 (trusty) gcc-5 and 6
    # another option is to use docker.
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: "3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - cmake-data # to use cmake 3.0 or more recent
            - cmake

    # Default environment of MacOS El Capitan
    # compiled using clang shipped with xcode8
    - os: osx
      osx_image: xcode8

    - os: osx
      osx_image: xcode8
      env: SHARED=ON

    # Default environment of MacOS Sierra
    # compiled using clang shipped with xcode8.3
    - os: osx
      osx_image: xcode8.3

before_install:
  # ISSUE: we may want to use '/scripts/install-deps-ubuntu.sh' in the future.
  # At this moment, travis-ci supports up to ubuntu 14.04 and this environment
  # does not recognize sudo apt-get install libglfw3-dev
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get install -y xorg-dev libglu1-mesa-dev libgl1-mesa-glx libglew-dev libjsoncpp-dev libeigen3-dev;
      ./util/scripts/make-documentation.sh;
    fi
  # scripts/install-deps-osx.sh works well
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew install python;
      ./util/scripts/install-deps-osx.sh;
    fi
  # - pip install numpy

script:
  # Build commands
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=$SHARED ../src/
  # make -j brings 'virtual memory exhausted: Cannot allocate memory' message
  # this is presumably due to limited memory space of travis-ci
  - make install
  - python -V
  # The following script has issues on SHARED = "ON"
  # - if [ "$SHARED" == "OFF" ]; then
  #     cd lib/Tutorial/Basic/ && python file_io.py
  #   fi
