matrix:

    notifications:
        email: false # turn off email notifications for build failure

    sudo: required

    language:
      - python
      - cpp

    include:

        - os: linux
          env:
          - distribution: ubuntu
          - version: 16.04

        - os: linux
          env:
          - distribution: ubuntu
          - version: 14.04

        # Default environment of MacOS El Capitan
        # compiled using clang shipped with xcode8
        - os: osx
          osx_image: xcode8

        # Default environment of MacOS Sierra
        # compiled using clang shipped with xcode8.3
        - os: osx
          osx_image: xcode8.3

    services:
        - docker

before_install:

    # Ubuntu systems Docker as travis-ci supports up to ubuntu 14.04.
    # pull and running docker on the background
    # installing dependencies. install sudo as it is not installed by default.
    # Note: Ubuntu 14.04 and this environment does not recognize sudo apt-get install libglfw3-dev
    # Comment in if-statement is now allowed.
    -   if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            docker pull ${distribution}:${version};
            docker run -d -v $(pwd):/Open3D ${distribution}:${version} /bin/bash -c 'while true; do sleep 1; done';
            docker exec $(docker ps -aq) /bin/bash -c 'apt-get update && apt-get -y install sudo cmake';
            if [ "$version" == "16.04" ]; then
                docker exec $(docker ps -aq) /bin/bash -c './Open3D/util/scripts/install-deps-ubuntu.sh';
            fi;
            if [ "$version" == "14.04" ]; then
                docker exec $(docker ps -aq) /bin/bash -c 'sudo apt-get install -y xorg-dev libglu1-mesa-dev libgl1-mesa-glx libglew-dev libjsoncpp-dev libeigen3-dev;';
            fi;
        fi

    # brew and cmake is already installed in MacOS images
    # scripts/install-deps-osx.sh works well
    # brew upgrade python; installs Python 3.6
    -   if [ "$TRAVIS_OS_NAME" == "osx" ]; then
            ./util/scripts/install-deps-osx.sh;
        fi

script:
    -   if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            docker exec $(docker ps -aq) /bin/bash -c 'cd /Open3D && mkdir build && cd build && cmake ../src/ && make';
        fi
    -   if [ "$TRAVIS_OS_NAME" == "osx" ]; then
            mkdir build && cd build && cmake ../src/ && make;
        fi
