[build-system]
requires = [
    "ipywidgets>=8.0.4",
    "pygments>=2.7.4",
    "jupyter_packaging~=0.12",
    "jupyterlab==4.*",
    "setuptools>=67.3.2",
    "wheel==0.46.3",
]
build-backend = "setuptools.build_meta"
