# Minium test for Open3D with OpenBLAS/LAPACK on both x86_64 and aarch64.
# This test is intentionally kept minimal and self-contained.

name: Ubuntu OpenBLAS CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

env:
  GCE_CLI_GHA_VERSION: '302.0.0'      # Fixed to avoid dependency on API changes

jobs:
  x86_64:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - name: Cancel outdated
        uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ github.token }}

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Maximize build space
        run: |
          source util/ci_utils.sh
          maximize_ubuntu_github_actions_build_space

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-openblas-x86_64-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-openblas-x86_64-ccache

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
            python-version: 3.6

      - name: Install dependencies
        run: |
            sudo apt-get --yes install ccache
            ccache -M 500M  # See .github/workflows/readme.md for ccache strategy.
            sudo apt-get update -q -y
            sudo apt-get install -y apt-utils build-essential git cmake
            sudo apt-get install -y python3-dev
            sudo apt-get install -y xorg-dev libglu1-mesa-dev ccache
            sudo apt-get install -y libblas-dev liblapack-dev liblapacke-dev
            python -m pip install -U pytest==6.0.1
            python -m pip install -U scipy==1.4.1
            python -m pip install -U wheel==0.35.1

      - name: Build and test
        run: |
          PATH=/usr/lib/ccache:$PATH
          ccache -s
          mkdir build
          cd build
          cmake \
            -DUSE_BLAS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=ON \
            -DBUILD_GUI=ON \
            -DCMAKE_C_COMPILER=gcc \
            -DCMAKE_CXX_COMPILER=g++ \
            -DBUILD_FILAMENT_FROM_SOURCE=ON \
            -DBUILD_TENSORFLOW_OPS=OFF \
            -DBUILD_PYTORCH_OPS=OFF \
            -DBUILD_UNIT_TESTS=ON \
            -DCMAKE_INSTALL_PREFIX=~/open3d_install \
            -DPYTHON_EXECUTABLE="$(which python3)" \
            ..
          make -j$(nproc)
          make tests -j$(nproc)
          make install-pip-package -j$(nproc)
          ./bin/tests --gtest_filter="-*Reduce*Sum*"
          pytest ../python/test/ --ignore ../python/test/ml_ops/  --ignore ../python/test/t/io/test_realsense.py
          ccache -s

  # ARM64 build can be slow, so it is spilt into multiple steps.
  # - arm64-step-1: compiles all 3rd-party libraries and upload the Open3D repo
  #   directory (including the build directory) as GitHub artifacts.
  # - arm64-step-2: downloads the Open3D directory from arm64-step-1, builds the
  #   rest of the library and runs the unit tests.
  arm64-step-1:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Maximize build space
        run: |
          source util/ci_utils.sh
          maximize_ubuntu_github_actions_build_space

      - name: GCloud CLI setup
        uses: google-github-actions/setup-gcloud@master
        with:
          version: ${{ env.GCE_CLI_GHA_VERSION }}
          service_account_key: ${{ secrets.GCE_SA_KEY_DOCS_CI }}
          project_id: ${{ secrets.GCE_DOCS_PROJECT }}
          export_default_credentials: true

      - name: Download ccache from GCS
        run: |
          gsutil -m cp -c -r gs://open3d-ci-cache/ccache-arm64 ~
          mv ~/ccache-arm64 ~/.ccache
          ls ~/.ccache

      - name: Build on ARM Container
        uses: uraimo/run-on-arch-action@v2.0.2
        with:
          # Ubuntu 20.04 has sufficiently new CMake
          arch: aarch64
          distro: ubuntu20.04

          # Speeds up builds
          githubToken: ${{ github.token }}

          # https://github.com/uraimo/run-on-arch-action/issues/4
          setup: |
            mkdir -p ~/.ccache

          # Mount cached directories in the container for faster builds
          dockerRunArgs: |
            --volume "${HOME}/.ccache:/root/.ccache"

          # Build and run Open3D tests
          run: |
            source util/ci_utils.sh
            install_arm64_dependencies
            source ${HOME}/venv/bin/activate
            PATH=/usr/lib/ccache:$PATH
            PATH=${HOME}/cmake-3.18-aarch64/bin:$PATH
            ccache -M 1.5G  # See .github/workflows/readme.md for ccache strategy.
            ccache -s
            mkdir build
            cd build
            cmake \
              -DCMAKE_BUILD_TYPE=Release \
              -DBUILD_SHARED_LIBS=ON \
              -DBUILD_GUI=ON \
              -DBUILD_LIBREALSENSE=ON \
              -DCMAKE_C_COMPILER=gcc \
              -DCMAKE_CXX_COMPILER=g++ \
              -DBUILD_TENSORFLOW_OPS=OFF \
              -DBUILD_PYTORCH_OPS=OFF \
              -DBUILD_UNIT_TESTS=ON \
              -DCMAKE_INSTALL_PREFIX=~/open3d_install \
              -DPYTHON_EXECUTABLE=$(which python) \
              ..
            make camera -j$(nproc) # open3d::camera is small and it triggers 3rd-party builds
            ccache -s

      - name: Upload ccache to GCS
        run: |
          gsutil -m rsync -r -d ~/.ccache/ gs://open3d-ci-cache/ccache-arm64/ || true

      # GITHUB_WORKSPACE      : /home/runner/work/Open3D/Open3D
      # 1. cd to              : /home/runner/work/Open3D
      # 2. compressed to      : /home/runner/work/Open3D/open3d-repo-dir-cache.tar.gz
      # 2. move to            : /home/runner/work/Open3D/Open3D/open3d-repo-dir-cache.tar.gz
      # 3. upload-artifact dir: /home/runner/work/Open3D/Open3D
      - name: Compress Open3D repo directory
        run: |
          sudo chown -R $(id -u):$(id -g) ${GITHUB_WORKSPACE}/build
          cd ${GITHUB_WORKSPACE}/..
          tar -czvf open3d-repo-dir-cache.tar.gz Open3D
          mv open3d-repo-dir-cache.tar.gz ${GITHUB_WORKSPACE}

      - name: Upload Open3D repo directory
        uses: actions/upload-artifact@v2
        with:
          name: open3d-repo-dir-cache
          path: open3d-repo-dir-cache.tar.gz
          retention-days: 1

  arm64-step-2:
    runs-on: ubuntu-20.04
    needs: [arm64-step-1]
    strategy:
      fail-fast: false
    steps:
      - name: Download Open3D repo directory
        uses: actions/download-artifact@v2
        with:
          name: open3d-repo-dir-cache

      # GITHUB_WORKSPACE: /home/runner/work/Open3D/Open3D
      # 1. downloaded to: /home/runner/work/Open3D/Open3D/open3d-repo-dir-cache.tar.gz
      # 2. move to      : /home/runner/work/Open3D/open3d-repo-dir-cache.tar.gz
      # 3. remove       : /home/runner/work/Open3D/Open3D
      # 4. inflate to   : /home/runner/work/Open3D/Open3D
      - name: Inflate Open3D repo directory
        run: |
          mv ${GITHUB_WORKSPACE}/open3d-repo-dir-cache.tar.gz ${GITHUB_WORKSPACE}/..
          cd ${GITHUB_WORKSPACE}/..
          rm -rf ${GITHUB_WORKSPACE}
          tar -xvf open3d-repo-dir-cache.tar.gz

      - name: Maximize build space
        run: |
          source util/ci_utils.sh
          maximize_ubuntu_github_actions_build_space

      - name: GCloud CLI setup
        uses: google-github-actions/setup-gcloud@master
        with:
          version: ${{ env.GCE_CLI_GHA_VERSION }}
          service_account_key: ${{ secrets.GCE_SA_KEY_DOCS_CI }}
          project_id: ${{ secrets.GCE_DOCS_PROJECT }}
          export_default_credentials: true

      - name: Download ccache from GCS
        run: |
          gsutil -m cp -c -r gs://open3d-ci-cache/ccache-arm64 ~
          mv ~/ccache-arm64 ~/.ccache
          ls ~/.ccache

      - name: Build on ARM Container
        uses: uraimo/run-on-arch-action@v2.0.2
        with:
          # Ubuntu 20.04 has sufficiently new CMake
          arch: aarch64
          distro: ubuntu20.04

          # Speeds up builds
          githubToken: ${{ github.token }}

          # https://github.com/uraimo/run-on-arch-action/issues/4
          setup: |
            mkdir -p ~/.ccache

          # Mount cached directories in the container for faster builds
          dockerRunArgs: |
            --volume "${HOME}/.ccache:/root/.ccache"

          # Build and run Open3D tests. No need to run CMake config again.
          run: |
            source util/ci_utils.sh
            install_arm64_dependencies
            source ${HOME}/venv/bin/activate
            PATH=/usr/lib/ccache:$PATH
            PATH=${HOME}/cmake-3.18-aarch64/bin:$PATH
            ccache -M 1.5G  # See .github/workflows/readme.md for ccache strategy.
            ccache -s
            cd build
            make -j$(nproc)
            make tests -j$(nproc)
            make install-pip-package -j$(nproc)
            ./bin/tests --gtest_filter="-*Reduce*Sum*"
            pytest ../python/test/ --ignore ../python/test/ml_ops/ --ignore ../python/test/test_color_map.py
            ccache -s

      - name: Upload ccache to GCS
        run: |
          gsutil -m rsync -r -d ~/.ccache/ gs://open3d-ci-cache/ccache-arm64/ || true
